- name: test VM creation and removal
  hosts: localhost
  connection: local

  vars:
    counter: 1

  tasks:

    # get cloud-specific OS vars

    - name: Set Cloud image
      include_tasks: "{{playbook_dir}}/os/{{cloud}}_os.yml"

    # Get cloud-specific instance type
    - name: get Instance type
      include_tasks: "{{playbook_dir}}/instance_types/{{cloud}}_instances.yml"
      when: instance_type is not defined

    # Used by Azure in order to sequentially spawn multiple VMs
    - name: Get random string of chars of length COUNT
      shell: openssl rand -hex 50 | head -c {{count}}
      register: output

    # turns that string into a proper YAML list
    - name: get list of chars
      set_fact:
        nums: "{{output.stdout | list}}"

    - name: Import AWS Instance Launch Tasks
      include_tasks: "{{playbook_dir}}/launch/launch_aws.yml"
      when: cloud == "aws"

    - name: Import GCE Instance Launch Tasks
      include_tasks: "{{playbook_dir}}/launch/launch_gce.yml"
      when: cloud == "gce"

    - name: Import Azure Instance Launch Tasks
      include_tasks: "{{playbook_dir}}/launch/launch_azure.yml"
      when: cloud == "azure"
      with_items: "{{nums}}"

    # It isnt done with every vm to save time while the others are booting
    - name: Wait for last Azure VM to start
      wait_for:
        host: "{{ azure_vm.properties.networkProfile.networkInterfaces.0.properties.ipConfigurations.0.properties.publicIPAddress.properties.ipAddress}}"
        port: 22
        state: started
      when: cloud == "azure"

- import_playbook: "{{playbook_dir}}/terminate.yml"
