- name: Run benchmark
  hosts: "{{benchmark}}"

  # Gets these variables from the localhost group

  vars:
    # User and password are set individually by the host
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore


  tasks:

    - Name: testing debug
      debug:
        msg: It works!
