- name: Run benchmark
  hosts: "{{benchmark}}"

  # Gets these variables from the localhost group

  vars:
    ansible_ssh_user: "{{ ssh_user }}"
    ansible_ssh_private_key_file: "{{ssh_key_dir}}"

  tasks:

    - name: Run High Performance Linpack (HPL)
      include_tasks: "{{playbook_dir}}/benchmarks/HPL/hpl.yml"
      ignore_errors: yes
      when: benchmark == "hpl"

    - name: Run Disk Benchmarker (Fio)
      include_tasks: "{{playbook_dir}}/benchmarks/fio/fio.yml"
      ignore_errors: yes
      when: benchmark == "fio"
