- name: Run benchmark
  hosts: "{{benchmark}}"

  # Gets these variables from the localhost group

  vars:
    ansible_user: "{{hostvars['localhost'].win_user}}"
    ansible_password: "{{hostvars['localhost'].win_pass}}"
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore


  tasks:

    - Name: testing debug
      debug:
        msg: It works!
