- name: Run benchmark
  hosts: "{{benchmark}}"
  gather_facts: false


  # Gets these variables from the localhost group

  vars:
    # User and password are set individually by the host
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore


  tasks:

    - name: Wait for connection to be come available
      wait_for_connection:
        timeout: 120 # two minutes
    
    - name: Gather facts about VM
      setup:

    - name: testing debug
      debug:
        msg: It works!
