- name: Terminate Cloud instances
  hosts: localhost
  connection: local

  # Since we are executing on localhost, the vars
  # we created in start.yml should still be active
  # As it was started all as one playbook

  tasks:

    - name: Clean up aws
      include_tasks: "{{playbook_dir}}/terminate/terminate_aws.yml"
      when:
        - cloud is defined
        - cloud == "aws"

    - name: Clean up gce
      include_tasks: "{{playbook_dir}}/terminate/terminate_gce.yml"
      when:
        - cloud is defined
        - cloud == "gce"

    - name: Clean up Azure
      include_tasks: "{{playbook_dir}}/terminate/terminate_azure.yml"
      when:
        - cloud is defined
        - cloud == "azure"
