- name: Provision Cloud Instance and Run HPL
  hosts: localhost
  connection: local

  vars:

    # Variables used by all clouds
    cloud: AWS
    region: us-west-2
    size: small # size will determine image and instance_type, which is cloud specific
    duration: 3600 # One hour

    # AWS Specific
    key: my_key

    # Google Cloud Specific vars
    pid: 1234
    serv_acct_email: 987-compute@compute@developer.gserviceaccount.com
    cred_file: ~/my_creds.json

    # Azure Specific vars
    azure_sub_id: 123-a23-32


    # Metadata for the parser
    test_type: HPL
    secret_key: super_secret # If passed in via extra-vars, it may not contain spaces
    ingress_url: 127.0.0.1

  tasks:

    # get cloud-specific facts (image, instance size depending on test_size)

    - name: Setting AWS Facts
      include_tasks: "{{playbook_dir}}/vars/aws_facts.yml"
      when: cloud == "AWS"

    - name: Setting GCE Facts
      include_tasks: "{{playbook_dir}}/vars/gce_facts.yml"
      when: cloud == "GCE"

    - name: Setting Azure Facts
      include_tasks: "{{playbook_dir}}/vars/azure_facts.yml"
      when: cloud == "Azure"


    # Launches the instances
    # TODO: enclose in yaml try-block

    - name: Import AWS Instance Launch Tasks
      include_tasks: "{{playbook_dir}}/launch/launch_aws.yml"
      when: cloud == "AWS"

    - name: Import GCE Instance Launch Tasks
      include_tasks: "{{playbook_dir}}/launch/launch_gce.yml"
      when: cloud == "GCE"

    - name: Import Azure Instance Launch Tasks
      include_tasks: "{{playbook_dir}}/launch/launch_azure.yml"
      when: cloud == "Azure"

    # Add new entries to in-memory host file for subsequent plays

    - name: Add AWS ips to HPL
      add_host:
        name: "{{ item.public_ip }}"
        groups: HPL
      with_items: "{{ ec2.instances }}"
      when: cloud == "AWS"

    - name: Add GCE ips to HPL
      add_host:
        name: "{{ item.public_ip }}"
        groups: HPL
      with_items: "{{ gce.instance_data }}"
      when: cloud == "GCE"

    - name: Add Azure ips to HPL
      add_host:
        name: "{{ item.public_ip }}"
        groups: HPL
      with_items: "{{ azure_vm.instances }}"
      when: cloud == "Azure"


# Run HPL Benchmark
# Includes Playbook

- import_playbook: hpl.yml
  when:
    - test_type is defined
    - test_type == "HPL"
