- name: Launch AWS EC2 Instance
  hosts: localhost
  connection: local
  become: false

  # defaults, which can be overridden with the --extra-vars flag
  vars:
    region: us-west-2
    instance_size: t2.micro
    sec_group: sg-b2355dc8 # SSH
    image: ami-47ee103f # Currently only supports CentOS
    key: my_aws_key # .pem
    BUILD_ID: 0 # jenkins build ID

  tasks:

    # Create Security Group

    - name: Launch EC2 instance
      ec2:
        group_id: "{{sec_group}}" # SSH
        instance_type: "{{ instance_size }}"
        image: "{{image}}"
        wait: true
        region: "{{ region }}"
        keypair: "{{ key }}"
        count: 1
      register: ec2

    - name: Wait for SSH to open
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"

    - name: Add name tag to instance
      ec2_tag:
        resource: "{{ item.id }}"
        region: "{{ region }}"
        state: present
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          Name: "AWS Small {{lookup('pipe','env TZ=America/Chicago date')}}"

        # Creates a new inventory file with a single entry
        # use temp files instead?
        # Need to fix in the case we launch 2 instances, as is the case with iperf3 benchmark
    - name: Create inventory file
      copy:
        content: |
          [HPL-instance]
          {{ item.public_ip }}

        dest: "~/inv-{{BUILD_ID}}.txt"

      with_items: "{{ ec2.instances }}"
